import type { ThemeConfig } from "antd";
import { theme as antdTheme } from "antd";

const neutral = {
    light: {
        primary: "#171717",
        primaryHover: "#000000",
        primaryText: "#ffffff",
        action: "#6252e8",
        actionHover: "#5141d5",
        actionActive: "#5041cc",
        actionShadow: "0 2px 6px rgba(98, 82, 232, 0.12)",
        border: "#e4e6ec",
        subtleBg: "#f8f9fb",
        elevatedBg: "#ffffff",
        itemHoverBg: "rgba(23, 23, 23, 0.06)",
        itemSelectedBg: "rgba(23, 23, 23, 0.1)",
        itemSelectedHoverBg: "rgba(23, 23, 23, 0.14)",
        itemText: "#171717",
        tableSelectedBg: "rgba(17, 17, 17, 0.05)",
        tableSelectedHoverBg: "rgba(17, 17, 17, 0.08)",
    },
    dark: {
        primary: "#fafafa",
        primaryHover: "#ffffff",
        primaryText: "#171717",
        action: "#aa9cff",
        actionHover: "#bcb1ff",
        actionActive: "#9787ed",
        actionShadow: "none",
        border: "#363331",
        subtleBg: "#242220",
        elevatedBg: "#1c1917",
        itemHoverBg: "rgba(250, 250, 249, 0.08)",
        itemSelectedBg: "rgba(250, 250, 249, 0.12)",
        itemSelectedHoverBg: "rgba(250, 250, 249, 0.16)",
        itemText: "#fafafa",
        tableSelectedBg: "rgba(255, 255, 255, 0.08)",
        tableSelectedHoverBg: "rgba(255, 255, 255, 0.12)",
    },
};

export function getAntThemeConfig(dark: boolean): ThemeConfig {
    const color = dark ? neutral.dark : neutral.light;

    return {
        algorithm: dark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
        cssVar: { key: dark ? "infinite-canvas-dark" : "infinite-canvas-light" },
        token: {
            borderRadius: 8,
            controlHeight: 32,
            controlHeightSM: 28,
            controlHeightLG: 40,
            colorBorder: color.border,
            colorBorderSecondary: color.border,
            colorPrimary: color.primary,
            colorInfo: color.primary,
            colorLink: color.primary,
            colorLinkHover: color.primaryHover,
            colorLinkActive: color.primary,
            colorTextLightSolid: color.primaryText,
            colorBgElevated: color.elevatedBg,
            controlItemBgHover: color.itemHoverBg,
            controlItemBgActive: color.itemSelectedBg,
            controlItemBgActiveHover: color.itemSelectedHoverBg,
        },
        components: {
            Button: {
                contentFontSize: 13,
                contentFontSizeSM: 13,
                contentFontSizeLG: 14,
                paddingInline: 12,
                paddingInlineSM: 8,
                iconGap: 6,
                colorPrimary: color.action,
                colorPrimaryHover: color.actionHover,
                colorPrimaryActive: color.actionActive,
                primaryColor: color.primaryText,
                primaryShadow: color.actionShadow,
                defaultShadow: "0 1px 2px rgba(0, 0, 0, 0.03)",
                defaultBorderColor: color.border,
                defaultHoverBg: color.subtleBg,
                defaultHoverColor: color.itemText,
                fontWeight: 500,
            },
            Input: {
                inputFontSize: 13,
                inputFontSizeSM: 13,
                inputFontSizeLG: 14,
                paddingInline: 10,
                activeBorderColor: color.action,
                hoverBorderColor: color.actionHover,
                activeShadow: "0 0 0 2px rgba(98, 82, 232, 0.1)",
            },
            Tabs: {
                titleFontSize: 14,
                horizontalItemPadding: "9px 0",
                horizontalItemGutter: 24,
                inkBarColor: color.action,
                itemSelectedColor: color.itemText,
                itemHoverColor: color.itemText,
            },
            Segmented: {
                fontSize: 13,
                trackBg: color.subtleBg,
                itemSelectedBg: color.elevatedBg,
                itemSelectedColor: color.itemText,
                itemHoverBg: color.itemHoverBg,
                trackPadding: 2,
            },
            Card: {
                borderRadiusLG: 12,
                boxShadowTertiary: "0 4px 16px rgba(0, 0, 0, 0.06)",
            },
            Dropdown: {
                colorBgElevated: color.elevatedBg,
                colorText: color.itemText,
                controlItemBgHover: color.itemHoverBg,
                controlItemBgActive: color.itemSelectedBg,
                controlItemBgActiveHover: color.itemSelectedHoverBg,
            },
            Menu: {
                popupBg: color.elevatedBg,
                itemActiveBg: color.itemSelectedBg,
                itemHoverBg: color.itemHoverBg,
                itemSelectedBg: color.itemSelectedBg,
                itemSelectedColor: color.itemText,
                darkPopupBg: neutral.dark.elevatedBg,
                darkItemHoverBg: neutral.dark.itemHoverBg,
                darkItemSelectedBg: neutral.dark.itemSelectedBg,
                darkItemSelectedColor: neutral.dark.itemText,
            },
            Select: {
                fontSize: 13,
                fontSizeSM: 13,
                fontSizeLG: 14,
                optionActiveBg: color.itemHoverBg,
                optionSelectedBg: color.itemSelectedBg,
                optionSelectedColor: color.itemText,
            },
            Table: {
                cellPaddingBlock: 13,
                cellFontSize: 13,
                rowSelectedBg: color.tableSelectedBg,
                rowSelectedHoverBg: color.tableSelectedHoverBg,
            },
            Form: {
                labelFontSize: 13,
                itemMarginBottom: 16,
                verticalLabelPadding: "0 0 6px",
            },
            Modal: { borderRadiusLG: 16, titleFontSize: 16 },
            Drawer: { fontSizeLG: 16 },
        },
    };
}
